name: ceph/ceph-csi

on: [push]

jobs:
  arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Build
      run: |
        git clone https://github.com/ceph/ceph-csi.git repo
        cd repo
        git checkout ${GIT_BRANCH}
        git tag -d ${GIT_BRANCH} || true # I know this is stupid, but why are there two tags here :)
        sed -i 's|tag \$(CSI_IMAGE)|tag $(CSI_IMAGE) docker.io/huettner94/|g' Makefile
        sed -i 's|\$(CONTAINER_CMD) build|docker buildx build --platform linux/arm64|' Makefile
        docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
        make ARCH=arm64 GOARCH=arm64
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GIT_BRANCH: v2.1.0
